// <auto-generated />
namespace webAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class projectAng : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(projectAng));
        
        string IMigrationMetadata.Id
        {
            get { return "202104160042007_projectAng"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
