// <auto-generated />
namespace webAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
<<<<<<< HEAD:webAPI/webAPI/Migrations/202104220047129_ss.Designer.cs
    public sealed partial class ss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ss));
        
        string IMigrationMetadata.Id
        {
            get { return "202104220047129_ss"; }
=======
    public sealed partial class sec : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sec));
        
        string IMigrationMetadata.Id
        {
            get { return "202104222040377_sec"; }
>>>>>>> dd7a7fa89fe4259342208520ec3ac71869b91b7b:webAPI/webAPI/Migrations/202104222040377_sec.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
